name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "5 10,22 * * *"
env:
  REGISTRY: ghcr.io
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - id: normalize-repository-name
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Pull container image
        run: docker pull ${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:latest

      - name: Run scraper
        env:
          MONEYMAN_CONFIG: ${{ secrets.MONEYMAN_CONFIG }}
        run: |
          docker run --rm \
            -e MONEYMAN_CONFIG \
            -e DEBUG="moneyman:*" \
            -e TZ="Asia/Jerusalem" \
            ${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:latest
