name: Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: "5 10,22 * * *"
env:
  REGISTRY: ghcr.io
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - id: normalize-repository-name
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Pull container image
        run: docker pull ${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:latest

      - name: Run scraper
        run: |
          echo "${{ secrets.MONEYMAN_CONFIG_B64 }}" | base64 --decode > config.json
          
          docker run --rm \
            -v ${{ github.workspace }}/config.json:/config.json \
            -e MONEYMAN_CONFIG_PATH=/config.json \
            -e MONEYMAN_UNSAFE_STDOUT="true" \
            -e DEBUG="moneyman:*" \
            -e TZ="Asia/Jerusalem" \
            ${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:latest
