name: Scrape

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - id: normalize-repository-name
        run: echo "repository=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Pull container image
        run: docker pull ${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:latest

      - name: Run scraper and extract secret log
        run: |
          cat << 'EOF' > config.json
          ${{ secrets.MONEYMAN_CONFIG }}
          EOF
          
          echo "מפעיל את הבוט..."
          docker run --name moneyman_bot \
            -v ${{ github.workspace }}/config.json:/config.json \
            -e MONEYMAN_CONFIG_PATH=/config.json \
            -e TZ="Asia/Jerusalem" \
            ${{ env.REGISTRY }}/${{ steps.normalize-repository-name.outputs.repository }}:latest || true
            
          echo "==== חושף את היומן הסודי של הבוט ===="
          docker cp moneyman_bot:/tmp/moneyman.log ./moneyman.log || echo "לא נוצר יומן"
          cat ./moneyman.log || true
          docker rm moneyman_bot || true
